/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t public/models/slot-machine.glb 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Body: THREE.Mesh
    CoinEntry: THREE.Mesh
    Cylinder002: THREE.Mesh
    Cylinder002_1: THREE.Mesh
    LeverAttach: THREE.Mesh
    Reel1: THREE.Mesh
    Reel1Caps: THREE.Mesh
    Reel2: THREE.Mesh
    Reel2Caps: THREE.Mesh
    Reel3: THREE.Mesh
    Reel3Caps: THREE.Mesh
  }
  materials: {
    Body: THREE.MeshStandardMaterial
    Lever: THREE.MeshStandardMaterial
    Handle: THREE.MeshStandardMaterial
    Reel: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/slot-machine.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Body.geometry} material={materials.Body} scale={[0.66, 1.098, 0.666]} />
      <mesh geometry={nodes.CoinEntry.geometry} material={materials.Body} scale={[0.66, 1.098, 0.666]} />
      <group position={[0.05, 1.352, 0.769]} scale={[0.018, 0.414, 0.018]}>
        <mesh geometry={nodes.Cylinder002.geometry} material={materials.Lever} />
        <mesh geometry={nodes.Cylinder002_1.geometry} material={materials.Handle} />
      </group>
      <mesh geometry={nodes.LeverAttach.geometry} material={materials.Body} scale={[0.66, 1.098, 0.666]} />
      <mesh geometry={nodes.Reel1.geometry} material={materials.Reel} position={[0.154, 1.972, -0.395]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.334, 0.193, 0.334]} />
      <mesh geometry={nodes.Reel1Caps.geometry} material={materials.Reel} position={[0.154, 1.972, -0.395]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.334, 0.193, 0.334]} />
      <mesh geometry={nodes.Reel2.geometry} material={materials.Reel} position={[0.154, 1.972, 0]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.334, 0.193, 0.334]} />
      <mesh geometry={nodes.Reel2Caps.geometry} material={materials.Reel} position={[0.154, 1.972, 0]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.334, 0.193, 0.334]} />
      <mesh geometry={nodes.Reel3.geometry} material={materials.Reel} position={[0.154, 1.972, 0.395]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.334, 0.193, 0.334]} />
      <mesh geometry={nodes.Reel3Caps.geometry} material={materials.Reel} position={[0.154, 1.972, 0.395]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.334, 0.193, 0.334]} />
    </group>
  )
}

useGLTF.preload('/slot-machine.glb')
